# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'easy1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1019, 865)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_27.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_19.addWidget(self.label_8)
        self.year_combo = QtWidgets.QComboBox(self.frame)
        self.year_combo.setObjectName("year_combo")
        self.year_combo.addItem("")
        self.horizontalLayout_19.addWidget(self.year_combo)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_19)
        self.filter_text = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_text.sizePolicy().hasHeightForWidth())
        self.filter_text.setSizePolicy(sizePolicy)
        self.filter_text.setObjectName("filter_text")
        self.horizontalLayout_20.addWidget(self.filter_text)
        self.search_btn = QtWidgets.QPushButton(self.frame)
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout_20.addWidget(self.search_btn)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_20)
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_27.addWidget(self.checkBox)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_29.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_22.addWidget(self.label_21)
        self.fuzeren = QtWidgets.QComboBox(self.frame_2)
        self.fuzeren.setObjectName("fuzeren")
        self.fuzeren.addItem("")
        self.fuzeren.addItem("")
        self.fuzeren.addItem("")
        self.fuzeren.addItem("")
        self.fuzeren.addItem("")
        self.fuzeren.addItem("")
        self.fuzeren.addItem("")
        self.horizontalLayout_22.addWidget(self.fuzeren)
        self.denglu = QtWidgets.QPushButton(self.frame_2)
        self.denglu.setObjectName("denglu")
        self.horizontalLayout_22.addWidget(self.denglu)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_29.addWidget(self.frame_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_26.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setInputMask("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_26.addWidget(self.lineEdit)
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_26.addWidget(self.comboBox_2)
        self.find_btn = QtWidgets.QPushButton(Form)
        self.find_btn.setObjectName("find_btn")
        self.horizontalLayout_26.addWidget(self.find_btn)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_26)
        self.start_btn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_btn.sizePolicy().hasHeightForWidth())
        self.start_btn.setSizePolicy(sizePolicy)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout_23.addWidget(self.start_btn)
        self.display = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display.sizePolicy().hasHeightForWidth())
        self.display.setSizePolicy(sizePolicy)
        self.display.setStyleSheet("background-color: rgb(255, 248, 170);")
        self.display.setAlignment(QtCore.Qt.AlignCenter)
        self.display.setObjectName("display")
        self.horizontalLayout_23.addWidget(self.display)
        self.progressBar = QtWidgets.QProgressBar(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_23.addWidget(self.progressBar)
        self.del_btn = QtWidgets.QPushButton(Form)
        self.del_btn.setObjectName("del_btn")
        self.horizontalLayout_23.addWidget(self.del_btn)
        self.save_btn = QtWidgets.QPushButton(Form)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_23.addWidget(self.save_btn)
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.main_table = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_table.sizePolicy().hasHeightForWidth())
        self.main_table.setSizePolicy(sizePolicy)
        self.main_table.setObjectName("main_table")
        self.main_table.setColumnCount(0)
        self.main_table.setRowCount(0)
        self.verticalLayout_12.addWidget(self.main_table)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(11, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.youxianji = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.youxianji.sizePolicy().hasHeightForWidth())
        self.youxianji.setSizePolicy(sizePolicy)
        self.youxianji.setStyleSheet("")
        self.youxianji.setObjectName("youxianji")
        self.youxianji.addItem("")
        self.youxianji.addItem("")
        self.youxianji.addItem("")
        self.youxianji.addItem("")
        self.youxianji.addItem("")
        self.youxianji.addItem("")
        self.youxianji.addItem("")
        self.horizontalLayout_7.addWidget(self.youxianji)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.weixiuleixing = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weixiuleixing.sizePolicy().hasHeightForWidth())
        self.weixiuleixing.setSizePolicy(sizePolicy)
        self.weixiuleixing.setStyleSheet("")
        self.weixiuleixing.setObjectName("weixiuleixing")
        self.weixiuleixing.addItem("")
        self.weixiuleixing.addItem("")
        self.weixiuleixing.addItem("")
        self.weixiuleixing.addItem("")
        self.weixiuleixing.addItem("")
        self.horizontalLayout_8.addWidget(self.weixiuleixing)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.begindate = QtWidgets.QDateEdit(Form)
        self.begindate.setStyleSheet("background-color: rgb(252, 228, 189);")
        self.begindate.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2025, 12, 31), QtCore.QTime(23, 59, 59)))
        self.begindate.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2010, 12, 31), QtCore.QTime(0, 0, 0)))
        self.begindate.setCalendarPopup(True)
        self.begindate.setObjectName("begindate")
        self.horizontalLayout.addWidget(self.begindate)
        self.begintime = QtWidgets.QTimeEdit(Form)
        self.begintime.setStyleSheet("background-color: rgb(252, 228, 189);")
        self.begintime.setCalendarPopup(False)
        self.begintime.setObjectName("begintime")
        self.horizontalLayout.addWidget(self.begintime)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.enddate = QtWidgets.QDateEdit(Form)
        self.enddate.setStyleSheet("background-color: rgb(252, 228, 189);")
        self.enddate.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2025, 12, 31), QtCore.QTime(23, 59, 59)))
        self.enddate.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2010, 12, 31), QtCore.QTime(0, 0, 0)))
        self.enddate.setCalendarPopup(True)
        self.enddate.setObjectName("enddate")
        self.horizontalLayout_2.addWidget(self.enddate)
        self.endtime = QtWidgets.QTimeEdit(Form)
        self.endtime.setStyleSheet("background-color: rgb(252, 228, 189);")
        self.endtime.setCalendarPopup(True)
        self.endtime.setTime(QtCore.QTime(18, 0, 0))
        self.endtime.setObjectName("endtime")
        self.horizontalLayout_2.addWidget(self.endtime)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_35.addLayout(self.verticalLayout_7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(24, -1, -1, -1)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_6 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_21.addWidget(self.label_6)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_21)
        self.zhuanye = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zhuanye.sizePolicy().hasHeightForWidth())
        self.zhuanye.setSizePolicy(sizePolicy)
        self.zhuanye.setStyleSheet("")
        self.zhuanye.setObjectName("zhuanye")
        self.zhuanye.addItem("")
        self.zhuanye.addItem("")
        self.zhuanye.addItem("")
        self.zhuanye.addItem("")
        self.zhuanye.addItem("")
        self.horizontalLayout_9.addWidget(self.zhuanye)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setContentsMargins(24, -1, -1, -1)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_31.addWidget(self.label_12)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_31)
        self.banzu = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.banzu.sizePolicy().hasHeightForWidth())
        self.banzu.setSizePolicy(sizePolicy)
        self.banzu.setStyleSheet("")
        self.banzu.setObjectName("banzu")
        self.banzu.addItem("")
        self.banzu.addItem("")
        self.banzu.addItem("")
        self.banzu.addItem("")
        self.banzu.addItem("")
        self.horizontalLayout_12.addWidget(self.banzu)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(12, -1, -1, -1)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_30.addWidget(self.label_4)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_30)
        self.mvp = QtWidgets.QLineEdit(Form)
        self.mvp.setStyleSheet("")
        self.mvp.setObjectName("mvp")
        self.horizontalLayout_17.addWidget(self.mvp)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.chengyuan = QtWidgets.QLineEdit(Form)
        self.chengyuan.setStyleSheet("")
        self.chengyuan.setObjectName("chengyuan")
        self.horizontalLayout_4.addWidget(self.chengyuan)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_35.addLayout(self.verticalLayout_5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.jizuleibie = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jizuleibie.sizePolicy().hasHeightForWidth())
        self.jizuleibie.setSizePolicy(sizePolicy)
        self.jizuleibie.setStyleSheet("")
        self.jizuleibie.setObjectName("jizuleibie")
        self.jizuleibie.addItem("")
        self.jizuleibie.addItem("")
        self.jizuleibie.addItem("")
        self.jizuleibie.addItem("")
        self.horizontalLayout_3.addWidget(self.jizuleibie)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(24, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.jizu = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jizu.sizePolicy().hasHeightForWidth())
        self.jizu.setSizePolicy(sizePolicy)
        self.jizu.setStyleSheet("")
        self.jizu.setObjectName("jizu")
        self.jizu.addItem("")
        self.jizu.addItem("")
        self.jizu.addItem("")
        self.jizu.addItem("")
        self.jizu.addItem("")
        self.jizu.addItem("")
        self.jizu.addItem("")
        self.horizontalLayout_5.addWidget(self.jizu)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setContentsMargins(24, -1, -1, -1)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_32.addWidget(self.label_5)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_32)
        self.bianma = QtWidgets.QLineEdit(Form)
        self.bianma.setStyleSheet("")
        self.bianma.setDragEnabled(False)
        self.bianma.setReadOnly(False)
        self.bianma.setObjectName("bianma")
        self.horizontalLayout_16.addWidget(self.bianma)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(24, -1, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_14 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.horizontalLayout_10.addLayout(self.verticalLayout_6)
        self.sum = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sum.sizePolicy().hasHeightForWidth())
        self.sum.setSizePolicy(sizePolicy)
        self.sum.setStyleSheet("")
        self.sum.setObjectName("sum")
        self.horizontalLayout_10.addWidget(self.sum)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_35.addLayout(self.verticalLayout_8)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.gzpleixing = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gzpleixing.sizePolicy().hasHeightForWidth())
        self.gzpleixing.setSizePolicy(sizePolicy)
        self.gzpleixing.setStyleSheet("")
        self.gzpleixing.setObjectName("gzpleixing")
        self.gzpleixing.addItem("")
        self.gzpleixing.addItem("")
        self.gzpleixing.addItem("")
        self.gzpleixing.addItem("")
        self.horizontalLayout_6.addWidget(self.gzpleixing)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(12, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.horizontalLayout_13.addLayout(self.verticalLayout_4)
        self.gelileixing = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gelileixing.sizePolicy().hasHeightForWidth())
        self.gelileixing.setSizePolicy(sizePolicy)
        self.gelileixing.setStyleSheet("")
        self.gelileixing.setObjectName("gelileixing")
        self.gelileixing.addItem("")
        self.gelileixing.addItem("")
        self.gelileixing.addItem("")
        self.gelileixing.addItem("")
        self.horizontalLayout_13.addWidget(self.gelileixing)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.verticalLayout_11.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setContentsMargins(12, -1, -1, -1)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_33.addWidget(self.label_19)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_33)
        self.gelizhuangtai = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gelizhuangtai.sizePolicy().hasHeightForWidth())
        self.gelizhuangtai.setSizePolicy(sizePolicy)
        self.gelizhuangtai.setStyleSheet("")
        self.gelizhuangtai.setObjectName("gelizhuangtai")
        self.gelizhuangtai.addItem("")
        self.gelizhuangtai.addItem("")
        self.gelizhuangtai.addItem("")
        self.gelizhuangtai.addItem("")
        self.gelizhuangtai.addItem("")
        self.gelizhuangtai.addItem("")
        self.gelizhuangtai.addItem("")
        self.gelizhuangtai.addItem("")
        self.gelizhuangtai.addItem("")
        self.gelizhuangtai.addItem("")
        self.gelizhuangtai.addItem("")
        self.gelizhuangtai.addItem("")
        self.gelizhuangtai.addItem("")
        self.gelizhuangtai.addItem("")
        self.gelizhuangtai.addItem("")
        self.horizontalLayout_14.addWidget(self.gelizhuangtai)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setContentsMargins(12, -1, -1, -1)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_34.addWidget(self.label_20)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_34)
        self.anquanbiaoshi = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anquanbiaoshi.sizePolicy().hasHeightForWidth())
        self.anquanbiaoshi.setSizePolicy(sizePolicy)
        self.anquanbiaoshi.setStyleSheet("")
        self.anquanbiaoshi.setObjectName("anquanbiaoshi")
        self.anquanbiaoshi.addItem("")
        self.anquanbiaoshi.addItem("")
        self.anquanbiaoshi.addItem("")
        self.anquanbiaoshi.addItem("")
        self.anquanbiaoshi.addItem("")
        self.anquanbiaoshi.addItem("")
        self.anquanbiaoshi.addItem("")
        self.horizontalLayout_15.addWidget(self.anquanbiaoshi)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.horizontalLayout_35.addLayout(self.verticalLayout_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setLineWidth(1)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.content = QtWidgets.QLineEdit(Form)
        self.content.setStyleSheet("background-color: rgb(252, 228, 189);")
        self.content.setObjectName("content")
        self.horizontalLayout_11.addWidget(self.content)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_18.addWidget(self.label_17)
        self.contentaddr = QtWidgets.QLineEdit(Form)
        self.contentaddr.setStyleSheet("background-color: rgb(252, 228, 189);")
        self.contentaddr.setObjectName("contentaddr")
        self.horizontalLayout_18.addWidget(self.contentaddr)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        self.glcs_table = QtWidgets.QTableWidget(Form)
        self.glcs_table.setObjectName("glcs_table")
        self.glcs_table.setColumnCount(0)
        self.glcs_table.setRowCount(0)
        self.verticalLayout_12.addWidget(self.glcs_table)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.btn_glcs_addrow = QtWidgets.QPushButton(Form)
        self.btn_glcs_addrow.setObjectName("btn_glcs_addrow")
        self.horizontalLayout_25.addWidget(self.btn_glcs_addrow)
        self.btn_glcs_delrow = QtWidgets.QPushButton(Form)
        self.btn_glcs_delrow.setObjectName("btn_glcs_delrow")
        self.horizontalLayout_25.addWidget(self.btn_glcs_delrow)
        self.text_find = QtWidgets.QLineEdit(Form)
        self.text_find.setObjectName("text_find")
        self.horizontalLayout_25.addWidget(self.text_find)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_25.addWidget(self.label_13)
        self.text_replace = QtWidgets.QLineEdit(Form)
        self.text_replace.setObjectName("text_replace")
        self.horizontalLayout_25.addWidget(self.text_replace)
        self.btn_replace = QtWidgets.QPushButton(Form)
        self.btn_replace.setObjectName("btn_replace")
        self.horizontalLayout_25.addWidget(self.btn_replace)
        self.verticalLayout_12.addLayout(self.horizontalLayout_25)
        self.ykcs_table = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ykcs_table.sizePolicy().hasHeightForWidth())
        self.ykcs_table.setSizePolicy(sizePolicy)
        self.ykcs_table.setObjectName("ykcs_table")
        self.ykcs_table.setColumnCount(0)
        self.ykcs_table.setRowCount(0)
        self.verticalLayout_12.addWidget(self.ykcs_table)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_8.setText(_translate("Form", "年份："))
        self.year_combo.setItemText(0, _translate("Form", "模板"))
        self.filter_text.setPlaceholderText(_translate("Form", "输入关键字搜索"))
        self.search_btn.setText(_translate("Form", "搜索"))
        self.checkBox.setText(_translate("Form", "定期工作"))
        self.label_21.setText(_translate("Form", "负责人："))
        self.fuzeren.setItemText(0, _translate("Form", "周军"))
        self.fuzeren.setItemText(1, _translate("Form", "胡毅"))
        self.fuzeren.setItemText(2, _translate("Form", "王志英"))
        self.fuzeren.setItemText(3, _translate("Form", "梁春红"))
        self.fuzeren.setItemText(4, _translate("Form", "云雯"))
        self.fuzeren.setItemText(5, _translate("Form", "车璐"))
        self.fuzeren.setItemText(6, _translate("Form", "范舒婷"))
        self.denglu.setText(_translate("Form", "登录"))
        self.lineEdit.setPlaceholderText(_translate("Form", "输入工单号"))
        self.comboBox_2.setItemText(0, _translate("Form", "2020"))
        self.comboBox_2.setItemText(1, _translate("Form", "2019"))
        self.comboBox_2.setItemText(2, _translate("Form", "2018"))
        self.find_btn.setText(_translate("Form", "查询"))
        self.start_btn.setText(_translate("Form", "开始"))
        self.display.setText(_translate("Form", "TextLabel"))
        self.del_btn.setText(_translate("Form", "删除"))
        self.save_btn.setText(_translate("Form", "保存"))
        self.label.setText(_translate("Form", "优先级："))
        self.youxianji.setItemText(0, _translate("Form", "立刻"))
        self.youxianji.setItemText(1, _translate("Form", "24小时内处理"))
        self.youxianji.setItemText(2, _translate("Form", "48小时内处理"))
        self.youxianji.setItemText(3, _translate("Form", "72小时内处理"))
        self.youxianji.setItemText(4, _translate("Form", "168小时内处理"))
        self.youxianji.setItemText(5, _translate("Form", "停机处理"))
        self.youxianji.setItemText(6, _translate("Form", "无"))
        self.label_2.setText(_translate("Form", "维修类型："))
        self.weixiuleixing.setItemText(0, _translate("Form", "定期工作"))
        self.weixiuleixing.setItemText(1, _translate("Form", "改进型检修"))
        self.weixiuleixing.setItemText(2, _translate("Form", "故障检修"))
        self.weixiuleixing.setItemText(3, _translate("Form", "状态检修"))
        self.weixiuleixing.setItemText(4, _translate("Form", "无"))
        self.label_10.setText(_translate("Form", "开始时间："))
        self.label_11.setText(_translate("Form", "结束时间："))
        self.label_6.setText(_translate("Form", "专业："))
        self.zhuanye.setItemText(0, _translate("Form", "汽机专业"))
        self.zhuanye.setItemText(1, _translate("Form", "锅炉专业"))
        self.zhuanye.setItemText(2, _translate("Form", "电气专业"))
        self.zhuanye.setItemText(3, _translate("Form", "热控专业"))
        self.zhuanye.setItemText(4, _translate("Form", "无"))
        self.label_12.setText(_translate("Form", "班组："))
        self.banzu.setItemText(0, _translate("Form", "热控计算机"))
        self.banzu.setItemText(1, _translate("Form", "热控程控班"))
        self.banzu.setItemText(2, _translate("Form", "热控自动一"))
        self.banzu.setItemText(3, _translate("Form", "热控自动二"))
        self.banzu.setItemText(4, _translate("Form", "无"))
        self.label_4.setText(_translate("Form", "负责人："))
        self.label_15.setText(_translate("Form", "班组成员："))
        self.label_7.setText(_translate("Form", "机组类别："))
        self.jizuleibie.setItemText(0, _translate("Form", "内蒙古丰泰发电厂"))
        self.jizuleibie.setItemText(1, _translate("Form", "呼和浩特科林热电厂"))
        self.jizuleibie.setItemText(2, _translate("Form", "科林城发热力"))
        self.jizuleibie.setItemText(3, _translate("Form", "无"))
        self.label_3.setText(_translate("Form", "机组："))
        self.jizu.setItemText(0, _translate("Form", "丰泰#1机组"))
        self.jizu.setItemText(1, _translate("Form", "丰泰#2机组"))
        self.jizu.setItemText(2, _translate("Form", "丰泰公用"))
        self.jizu.setItemText(3, _translate("Form", "科林新#3机组"))
        self.jizu.setItemText(4, _translate("Form", "科林新#4机组"))
        self.jizu.setItemText(5, _translate("Form", "科林公用"))
        self.jizu.setItemText(6, _translate("Form", "无"))
        self.label_5.setText(_translate("Form", "编码："))
        self.label_14.setText(_translate("Form", "人数："))
        self.label_9.setText(_translate("Form", "工作票类型："))
        self.gzpleixing.setItemText(0, _translate("Form", "热力机械工作票"))
        self.gzpleixing.setItemText(1, _translate("Form", "热力机械外包工作票"))
        self.gzpleixing.setItemText(2, _translate("Form", "电气工作票"))
        self.gzpleixing.setItemText(3, _translate("Form", "无"))
        self.label_18.setText(_translate("Form", "隔离类型："))
        self.gelileixing.setItemText(0, _translate("Form", "电气隔离"))
        self.gelileixing.setItemText(1, _translate("Form", "机械隔离"))
        self.gelileixing.setItemText(2, _translate("Form", "电气及机械隔离"))
        self.gelileixing.setItemText(3, _translate("Form", "无"))
        self.label_19.setText(_translate("Form", "隔离状态："))
        self.gelizhuangtai.setItemText(0, _translate("Form", "备用"))
        self.gelizhuangtai.setItemText(1, _translate("Form", "不停电"))
        self.gelizhuangtai.setItemText(2, _translate("Form", "断开"))
        self.gelizhuangtai.setItemText(3, _translate("Form", "关"))
        self.gelizhuangtai.setItemText(4, _translate("Form", "关闭、停电"))
        self.gelizhuangtai.setItemText(5, _translate("Form", "合上"))
        self.gelizhuangtai.setItemText(6, _translate("Form", "解除自动"))
        self.gelizhuangtai.setItemText(7, _translate("Form", "开"))
        self.gelizhuangtai.setItemText(8, _translate("Form", "停电"))
        self.gelizhuangtai.setItemText(9, _translate("Form", "停运"))
        self.gelizhuangtai.setItemText(10, _translate("Form", "停运断电"))
        self.gelizhuangtai.setItemText(11, _translate("Form", "退出保护"))
        self.gelizhuangtai.setItemText(12, _translate("Form", "退出监视"))
        self.gelizhuangtai.setItemText(13, _translate("Form", "退出连锁"))
        self.gelizhuangtai.setItemText(14, _translate("Form", "无"))
        self.label_20.setText(_translate("Form", "安全标识："))
        self.anquanbiaoshi.setItemText(0, _translate("Form", "禁止操作，有人工作"))
        self.anquanbiaoshi.setItemText(1, _translate("Form", "禁止合闸，有人工作"))
        self.anquanbiaoshi.setItemText(2, _translate("Form", "禁止攀登"))
        self.anquanbiaoshi.setItemText(3, _translate("Form", "由此上下"))
        self.anquanbiaoshi.setItemText(4, _translate("Form", "在此工作"))
        self.anquanbiaoshi.setItemText(5, _translate("Form", "止步，高压危险"))
        self.anquanbiaoshi.setItemText(6, _translate("Form", "无"))
        self.label_16.setText(_translate("Form", "工作内容："))
        self.label_17.setText(_translate("Form", "内容及地点："))
        self.btn_glcs_addrow.setText(_translate("Form", "增加"))
        self.btn_glcs_delrow.setText(_translate("Form", "删除"))
        self.label_13.setText(_translate("Form", "----->"))
        self.btn_replace.setText(_translate("Form", "替换"))
